/**
 * USER
 */
export const SIGNUP_USER_REQUEST = 'SIGNUP_USER_REQUEST';
export const SIGNUP_USER_SUCCESS = 'SIGNUP_USER_SUCCESS';
export const SIGNUP_USER_FAILURE = 'SIGNUP_USER_FAILURE';

export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';

export const LOGOUT_USER = 'LOGOUT_USER';

export const GET_USER_SESSION_REQUEST = 'GET_USER_SESSION_REQUEST';
export const GET_USER_SESSION_SUCCESS = 'GET_USER_SESSION_SUCCESS';

export const SET_USER_PROFILE_REQUEST = 'SET_USER_PROFILE_REQUEST';
export const SET_USER_PROFILE_SUCCESS = 'SET_USER_PROFILE_SUCCESS';
export const SET_USER_PROFILE_FAILURE = 'SET_USER_PROFILE_FAILURE';

/**
 * UI
 */
export const SET_UI_ERROR = 'SET_UI_ERROR';
export const RESET_UI_ERROR = 'RESET_UI_ERROR';

export const SHOW_BOARDS_EXPLORER = 'SHOW_BOARDS_EXPLORER';
export const HIDE_BOARDS_EXPLORER = 'HIDE_BOARDS_EXPLORER';

export const FOCUS_HEADER_SEARCH = 'FOCUS_HEADER_SEARCH';
export const BLUR_HEADER_SEARCH = 'BLUR_HEADER_SEARCH';

export const SHOW_CREATE_MENU = 'SHOW_CREATE_MENU';
export const HIDE_CREATE_MENU = 'HIDE_CREATE_MENU';

export const SHOW_NOTIFICATIONS = 'SHOW_NOTIFICATIONS';
export const HIDE_NOTIFICATIONS = 'HIDE_NOTIFICATIONS';

export const SHOW_USER_MENU = 'SHOW_USER_MENU';
export const HIDE_USER_MENU = 'HIDE_USER_MENU';

export const SHOW_BOARD_MENU = 'SHOW_BOARD_MENU';
export const HIDE_BOARD_MENU = 'HIDE_BOARD_MENU';

/**
 * Cards
 */
export const SHOW_CARD_DETAIL = 'SHOW_CARD_DETAIL ';
export const HIDE_CARD_DETAIL = 'HIDE_CARD_DETAIL ';

export const SHOW_LABEL_TEXT = 'SHOW_LABEL_TEXT';
export const HIDE_LABEL_TEXT = 'HIDE_LABEL_TEXT';
